# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gmd_deflation_cpp <- function(X, Q, R, k, thr = 1e-5) {
    .Call('_neuroca_gmd_deflation_cpp', PACKAGE = 'neuroca', X, Q, R, k, thr)
}

gmdLA_cpp <- function(X, Q, R, k) {
    .Call('_neuroca_gmdLA_cpp', PACKAGE = 'neuroca', X, Q, R, k)
}

